app_root_redirect:
    path: /
    controller: App\Controller\RedirectionController::index
    methods: [GET]
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix:
        fr: /fr
        en: /en
